services:
- type: web
  name: meilisearch
  env: docker
  dockerCommand: ./render/Dockerfile
  envVars:
  - key: MEILI_DB_PATH
    value: /var/lib/meilifiles
  - key: MEILI_MASTER_KEY
    generateValue: true
  disk:
    name: data
    mountPath: /var/lib/meilifiles
    sizeGB: 10
